id: I8F61E934
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:51:11+00:00'
last_modified: '2022-06-09T04:36:06.554018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14735
  title: གཞས་གར་ངོ་མཚར་ལྟད་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7BBA:
      image_group_id: I2PD17814
      title: Volume 1 of gzhas gar ngo mtshar ltad mo/
      total_pages: 344
      order: 1
      base_file: 7BBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
