id: P008114
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14735
  title: གཞས་གར་ངོ་མཚར་ལྟད་མོ།
  author: ''
  volumes:
    9556f1583c41431aa5b48ed6f3dd53dc:
      image_group_id: I2PD17814
      title: Volume 1 of gzhas gar ngo mtshar ltad mo/
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
