id: P008114
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14735
  title: གཞས་གར་ངོ་མཚར་ལྟད་མོ།
  author: ''
  volumes:
    892f617d58a646a0bd448ff701be7fc3:
      image_group_id: I2PD17814
      title: ''
      volume_number: 1
      total_pages: 344
ebook_metadata:
  title: གཞས་གར་ངོ་མཚར་ལྟད་མོ།
  author: ''
  sku: P008114
  cover: cover.jpg
  layers:
  - pagination
